services:
  pisite:
    name: pisite
    image: localhost/pisite/web:test
    build:
      context: ./services/web
      dockerfile: Containerfile
    devices:
      - ${GPIO_DEVICE:?error}:${GPIO_DEVICE:?error}
    ports:
      - "${PORT:?error}:${PORT:?error}"
    command: [
      "uv",
      "run",
      "gunicorn",
      "-w",
      "1",
      "-b",
      "${INTERFACE:?error}",
      "pisite.app:create_app( \
        '${FLASK_CONFIG_MOUNTED_FILE:?error}', \
        '${GPIO_DEVICE:?error}', \
        '${SERVICE_MONITOR_FILE:?error}', \
        '${CPU_TEMPERATURE_MOUNTED_FILE:?error}', \
      )"
    ]
    restart: unless-stopped
    volumes:
      # FIXME change to a `config` when available in podman compose.
      - ${FLASK_CONFIG_HOST_FILE:?error}:/${FLASK_CONFIG_MOUNTED_FILE:?error}:ro
      - service-monitor:/${SERVICE_MONITOR_VOLUME:?error}:ro
      - ${CPU_TEMPERATURE_HOST_FILE:?error}:${CPU_TEMPERATURE_MOUNTED_FILE:?error}:ro
  service-monitor:
    image: localhost/pisite/service-monitor:test
    build:
      context: ./services/service-monitor
      dockerfile: Containerfile
    command: ["/bin/sh", "run.sh", "${SERVICE_MONITOR_FILE:?error}", "60"]
    restart: unless-stopped
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:ro
      - service-monitor:${SERVICE_MONITOR_VOLUME:?error}


volumes:
  service-monitor:
